from RMMBench.tasks.manipulation.pick_snack_single import *
from RMMBench.tasks.manipulation.pick_multi_snack_single_container import *
from RMMBench.tasks.manipulation.wash_fruit_veg import *
from RMMBench.tasks.manipulation.wash_multi_fruit_veg import *
from RMMBench.tasks.manipulation.wash_fruit_shelf import *
from RMMBench.tasks.manipulation.cook_meat_pan_stove import *
from RMMBench.tasks.manipulation.reheat_microwave import *
from RMMBench.tasks.manipulation.store_meat_fridge import *
from RMMBench.tasks.manipulation.prepare_meat_tool import *
from RMMBench.tasks.manipulation.pick_kitchen_tool import *
from RMMBench.tasks.manipulation.pick_multi_kitchen_tool import *
from RMMBench.tasks.manipulation.pick_bread_toaster import *
from RMMBench.tasks.manipulation.bring_cold_drink import *
from RMMBench.tasks.manipulation.pick_bread_prep import *
from RMMBench.tasks.manipulation.pick_drink_choice_no_fridge import *
from RMMBench.tasks.manipulation.store_item_fridge import *
from RMMBench.tasks.manipulation.fix_burnt_bread import *
from RMMBench.tasks.manipulation.classify_snacks_on_shelf import *
from RMMBench.tasks.manipulation.uncover_object import *
from RMMBench.tasks.manipulation.store_cabinet import *
from RMMBench.tasks.manipulation.select_same_class_cabinet import *
